### PR TITLE
Fix problem with html comments in gutenberg block content

### PR DESCRIPTION
**Pull request by mrudzki91**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmltm-4021

### CODE REVIEW

**Review by andreasciamanna — DISMISSED** [review]

**Comment by andreasciamanna** [comment]
@mrudzki91 Automated checks seem to be failing

**Review by andreasciamanna — APPROVED** [review]

**Review by dgwatkins — COMMENTED** [review]
@mrudzki91 Isn't it the same to add another line to the strtr() array argument instead of adding str_replace()?

**Comment by mrudzki91** [comment]
> @mrudzki91 Isn't it the same to add another line to the strtr() array argument instead of adding str_replace()?

@dgwatkins It isn't because the incorrect '--/>' string is produced by `strtr()` in some cases. That's why we need to run another replace on it's result.

**Review by dgwatkins — APPROVED** [review]
:+1: @mrudzki91

**Pull request merged**
