### PR TITLE
Use correct options for encoding JSON attributes.

### PR DESCRIPTION
**Pull request by dgwatkins**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6834

### CODE REVIEW

**Comment by andreasciamanna** [comment]
@OnTheGoSystems/compatibility

**Review by strategio — DISMISSED** [review]
@dgwatkins, I mentionned in the ticket that we should try to have a CC test for this issue. That's because it involves the way data is sent to the server and the implementation of WP and WPML Core.

**Comment by dgwatkins** [comment]
Sorry @strategio 

I just dismissed your review because I saw how Konrad tested this sort of change and did the same.

As for the CC test,  I will make sure its done.

**Review by brucepearson — DISMISSED** [review]
@dgwatkins It looks good to me. +1

**Review by strategio — DISMISSED** [review]
+1

**Pull request merged**
