### PR TITLE
Unicode is not escaped in Gutenberg block attributes

### PR DESCRIPTION
**Pull request by kkarpieszuk**
- added flag to escape unicode chars while doing json_encode

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6540

### CODE REVIEW

**Comment by kkarpieszuk** [comment]
@strategio please review. It comes from your suggestion here https://github.com/OnTheGoSystems/wpml-page-builders-gutenberg/pull/30

**Comment by strategio** [comment]
@kkarpieszuk, as commented in YT, I suggest you target your PR to `develop` branch so we'll merge it for a WPML version which is not supposed to run PHP version lt 5.6.

+1

**Review by strategio — DISMISSED** [review]

**Comment by kkarpieszuk** [comment]
@strategio is there an easy way to change this to be based on develop, not master? I didn't see I was working on wrong branch. 

If not, I will cone it again, chdckout develop, then create a branch and then create MR, ok?

btw, I am getting emails now, so just reply here :)

**Comment by strategio** [comment]
@kkarpieszuk, you can change the target branch in the PR (click "edit" next to the PR title).

Then, I suggest:
1. `git checkout wpmlcore-6540`
2. `git branch wpmlcore-6540-master`
3. `git checkout develop`
4. `git branch -D wpmlcore-6540`
5. `git checkout wpmlcore-6540`
6. `git cherry-pick 7a6f33bf84dba456813db6ec2dae707a62e4b018`
7. `git push origin wpmlcore-6540 --force-with-lease`

**Comment by kkarpieszuk** [comment]
done, @strategio please check if correctly :)

**Comment by strategio** [comment]
This is not correct @kkarpieszuk, we should have one commit only in this PR. Let me try to fix it.

**Comment by strategio** [comment]
I updated your branch @kkarpieszuk, please check if it's OK. We should also have this change reflected in our unit tests. Could you try to add so Polish chars in the attribute values here => https://github.com/OnTheGoSystems/wpml-page-builders-gutenberg/blob/master/tests/phpunit/tests/test-wpml-gutenberg-integration.php#L153

You will also have to add the new parameter `JSON_UNESCAPED_UNICODE` in https://github.com/OnTheGoSystems/wpml-page-builders-gutenberg/blob/master/tests/phpunit/tests/test-wpml-gutenberg-integration.php#L182.

**Comment by kkarpieszuk** [comment]
@strategio done, please review

**Review by strategio — APPROVED** [review]
+1 @kkarpieszuk

**Comment by strategio** [comment]
@OnTheGoSystems/wpml, please give a second review.

**Comment by kkarpieszuk** [comment]
@OnTheGoSystems/wpml, I would like to remind you about this :) It is quite required for ACF Blocks

**Review by andreasciamanna — APPROVED** [review]

**Comment by dimitrismitsis** [comment]
@strategio or @kkarpieszuk can you please rebase properly this branch?  
I'm getting some conflicts and the commits don't look ok.

**Comment by dimitrismitsis** [comment]
Also, @kkarpieszuk or @andreasciamanna could you confirm that the target branch is ok here?  
We really want this to be part of 4.3.0 instead of a hot-fix version?

**Comment by andreasciamanna** [comment]
@dimitrismitsis indeed, that's a hot-fix. Unless it requires major changes in the code, I don't see why we should target **develop**.

**Comment by kkarpieszuk** [comment]
sorry, I am closing as again I don't want to trap myself in rebasing/branching conflicts and I have created new branch with new MR 

https://github.com/OnTheGoSystems/wpml-page-builders-gutenberg/pull/36

**Pull request closed without merging**
