### PR TITLE
Break/delay direct dependencies to TM - https://onthegosystems.myjetb…

### PR DESCRIPTION
**Pull request by brucepearson**
…rains.com/youtrack/issue/wpmltm-3548

@strategio I suggest we do something like this to remove the direct dependencies on TM when objects are constructed via DIC.

### CODE REVIEW

**Review by strategio — DISMISSED** [review]
Nice idea @brucepearson +1

**Review by andreasciamanna — DISMISSED** [review]

**Comment by brucepearson** [comment]
@dimitrismitsis This needs to be merged. It fixes the underlying problem in the future.

**Comment by dimitrismitsis** [comment]
@BruceOnTheGo some checks are failing here

**Comment by andreasciamanna** [comment]
I suppose this PR is not needed for now, since I'm putting my changes on hold.

**Pull request merged**
